import assert from 'node:assert/strict';
import {spawnSync} from 'node:child_process';
import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {evaluatePreflight} from '../tools/check_v22_cross_device_drive_preflight.mjs';

const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const artifact=path.join(root,'artifacts','physical_cross_device_v22_drive_real_v1.json');
const pcUrl=process.env.NOTEPLUS_PC_V22_URL||'';
const androidUrl=process.env.NOTEPLUS_ANDROID_V22_URL||'';
const sourceHead=process.env.NOTEPLUS_SOURCE_HEAD||'';
const marker=`REAL-CROSS-DEVICE-${Date.now()}`;
const delay=ms=>new Promise(resolve=>setTimeout(resolve,ms));
const commandText=(command,args)=>{const result=spawnSync(command,args,{encoding:'utf8',windowsHide:true,shell:process.platform==='win32'});return result.status===0?String(result.stdout||''):'';};
const poll=async(check,timeout=60000,interval=300)=>{const end=Date.now()+timeout;let last;while(Date.now()<end){try{last=await check();if(last)return last;}catch(error){last=error;}await delay(interval);}throw last instanceof Error?last:new Error('poll timeout');};
function clientId(){const text=fs.readFileSync(path.join(root,'google-drive-config-v18.js'),'utf8');return /clientId:\s*["']([^"']+)["']/.exec(text)?.[1]||'';}
function projects(){const text=commandText('gcloud',['projects','list','--format=value(projectNumber)','--limit=100']);return text?text.split(/\r?\n/).map(value=>value.trim()).filter(Boolean):null;}

class CdpTarget{
 constructor(url){this.url=url;this.nextId=1;this.pending=new Map();}
 async connect(){this.ws=new WebSocket(this.url);this.ws.onmessage=event=>{const message=JSON.parse(String(event.data)),pending=this.pending.get(message.id);if(!pending)return;this.pending.delete(message.id);message.error?pending.reject(new Error(`${pending.method}: ${message.error.message}`)):pending.resolve(message.result||{});};await new Promise((resolve,reject)=>{this.ws.onopen=resolve;this.ws.onerror=reject;});}
 send(method,params={},timeout=30000){const id=this.nextId++;return new Promise((resolve,reject)=>{const timer=setTimeout(()=>{this.pending.delete(id);reject(new Error(`${method}: response timeout`));},timeout);this.pending.set(id,{method,resolve:value=>{clearTimeout(timer);resolve(value);},reject:error=>{clearTimeout(timer);reject(error);}});this.ws.send(JSON.stringify({id,method,params}));});}
 async evaluate(expression){const response=await this.send('Runtime.evaluate',{expression,awaitPromise:true,returnByValue:true,userGesture:true},120000);if(response.exceptionDetails)throw new Error(response.exceptionDetails.exception?.description||response.exceptionDetails.text||'Runtime evaluation failed');return response.result?.value;}
 close(){try{this.ws?.close();}catch{}}
}
class BrowserEndpoint{
 constructor(httpUrl,label){this.httpUrl=httpUrl;this.label=label;}
 async targets(){const response=await fetch(this.httpUrl+'/json/list');assert.equal(response.ok,true,`${this.label} CDP endpoint unavailable`);return response.json();}
 async main(){const candidates=(await this.targets()).filter(item=>item.type==='page'&&/^https?:/i.test(item.url)&&item.webSocketDebuggerUrl).sort((a,b)=>Number(/noteplusp/i.test(b.url))-Number(/noteplusp/i.test(a.url))).slice(0,16);for(const item of candidates){const cdp=new CdpTarget(item.webSocketDebuggerUrl);try{await cdp.connect();await cdp.send('Page.enable',{},3000);await cdp.send('Runtime.enable',{},3000);return {cdp,originalUrl:item.url};}catch{cdp.close();}}throw new Error(`${this.label} usable browser tab unavailable`);}
 async advanceGoogle(main){const deadline=Date.now()+120000;while(Date.now()<deadline){if(await main.evaluate('Boolean(window.noteplusCloud?.status?.().user)').catch(()=>false))return true;for(const item of (await this.targets()).filter(target=>target.type==='page'&&/^https:\/\/accounts\.google\.com\//.test(target.url)&&target.webSocketDebuggerUrl)){const popup=new CdpTarget(item.webSocketDebuggerUrl);try{await popup.connect();await popup.send('Runtime.enable',{},3000);const action=await popup.evaluate(`(()=>{const visible=e=>e&&e.getClientRects().length;const account=[...document.querySelectorAll('[data-identifier],[data-authuser]')].find(visible);if(account){account.click();return 'account';}const controls=[...document.querySelectorAll('button,[role="button"],a')].filter(visible);const pick=controls.find(e=>/^(계속|Continue|허용|Allow|고급|Advanced)$/i.test((e.textContent||'').trim()))||controls.find(e=>/안전하지 않음|unsafe/i.test(e.textContent||''));if(pick){pick.click();return 'consent';}return 'wait';})()`);if(action!=='wait')await delay(1000);}catch{}finally{popup.close();}}await delay(500);}return false;}
}
async function openApp(cdp,url){await cdp.send('Page.navigate',{url},90000);await poll(()=>cdp.evaluate("document.readyState==='complete'||document.readyState==='interactive'"),90000);await poll(()=>cdp.evaluate("Boolean(window.state&&window.storageReady&&typeof window.storageReady.then==='function')"),60000);await cdp.evaluate('window.storageReady');await cdp.evaluate("document.querySelector('#v22SkipWelcome')?.click();true");}
const localSnapshot=cdp=>cdp.evaluate('({json:JSON.stringify(state),signature:stateSignature(state)})');
async function restoreLocal(cdp,snapshot,attachmentId){await cdp.evaluate(`(async()=>{state=migrateState(JSON.parse(${JSON.stringify(snapshot.json)}));sanitizeAllNoteHtml(state);await writeStateAndAttachments([],${JSON.stringify(attachmentId)}?[${JSON.stringify(attachmentId)}]:[],null);render();if(stateSignature(state)!==${JSON.stringify(snapshot.signature)})throw new Error('original signature mismatch');return true;})()`);}
async function signIn(endpoint,cdp){if(await cdp.evaluate('Boolean(window.noteplusCloud?.status?.().user)'))return;await cdp.evaluate("document.querySelector('#googleSignInBtn').click();true");assert.equal(await endpoint.advanceGoogle(cdp),true,'Google OAuth did not complete');}
async function capturePriorDrive(cdp){return cdp.evaluate(`(async()=>{try{const bundle=await noteplusCloud.downloadCurrentSnapshot(),attachments=[];for(const item of bundle.manifest.attachments)attachments.push({id:item.id,blob:await noteplusCloud.downloadAttachment(bundle.pointer.snapshotId,item,bundle.accountUid),mime:item.mime,sha256:item.sha256});const manifestText=JSON.stringify(bundle.manifest);window.__crossDevicePriorDrive={snapshotId:bundle.pointer.snapshotId,manifestText,manifestSha256:await sha256Text(manifestText),attachments,counts:bundle.manifest.counts};return true;}catch{return false;}})()`);}
async function createSeed(cdp){return cdp.evaluate(`(async()=>{const now=Date.now(),note={id:uid(),title:${JSON.stringify(marker)},body:'PC에서 만든 합성 교차기기 Drive 검사',bodyHtml:'<p>PC에서 만든 합성 교차기기 Drive 검사</p>',notebook:state.notebooks[0]||'개인',tags:['실제교차기기검사'],created:now-1000,updated:now,attachmentIds:[],favorite:false,history:[]};const blob=new Blob(['%PDF-1.4\\nNotePlusP cross-device proof\\n%%EOF\\n'],{type:'application/pdf'}),id='att_'+uid(),meta={id,noteId:note.id,name:'noteplusp-cross-device.pdf',mime:'application/pdf',size:blob.size,created:now,sha256:await sha256Blob(blob)};note.attachmentIds=[id];state.notes.push(note);await writeStateAndAttachments([{meta,blob}],[],null);render();return id;})()`);}
async function backup(cdp){await cdp.evaluate("document.querySelector('#cloudBackupBtn').click();true");await poll(()=>cdp.evaluate('!cloudSnapshotInFlight&&Boolean(v22Status.lastBackupId)'),180000);return cdp.evaluate('v22Status.lastBackupId');}
async function restoreRemote(cdp){await cdp.evaluate(`(async()=>{const empty=cloneState(state);empty.notes=[];empty.trash=[];empty.lastImportUndo=null;empty.lastImportReport=null;empty.preferences.snapshots=[];empty.preferences.conflictVaultV1=[];state=migrateState(empty);await persist();render();return true;})()`);await cdp.evaluate("document.querySelector('#cloudRestoreBtn').click();true");await poll(()=>cdp.evaluate('Boolean(pendingCloudRestore)&&!cloudSnapshotInFlight'),180000);await cdp.evaluate("document.querySelector('#cloudRestoreBtn').click();true");await poll(()=>cdp.evaluate("Boolean(document.querySelector('[data-v22-restore=\"remote\"]')?.getClientRects().length)"),30000);await cdp.evaluate("document.querySelector('[data-v22-restore=\"remote\"]').click();true");await poll(()=>cdp.evaluate(`!cloudSnapshotInFlight&&state.notes.some(note=>note.title===${JSON.stringify(marker)}||note.title===${JSON.stringify(marker+'-ANDROID')})`),180000);}

const preflight=evaluatePreflight({clientId:clientId(),pcUrl,androidUrl,adbOutput:commandText('adb',['devices','-l']),cloudProjectNumbers:projects()});
assert.equal(preflight.result,'READY',`cross-device preflight blocked: ${preflight.blockers.join(',')}`);
const pcEndpoint=new BrowserEndpoint(process.env.NOTEPLUS_PC_CDP||'http://127.0.0.1:9223','PC');
const androidEndpoint=new BrowserEndpoint(process.env.NOTEPLUS_ANDROID_CDP||'http://127.0.0.1:9222','Android');
const pc=await pcEndpoint.main(),android=await androidEndpoint.main();let pcSnapshot,androidSnapshot,attachmentId='',priorDrive=false,priorRestored=false,pcRestored=false,androidRestored=false;
try{
 await openApp(pc.cdp,pcUrl);await openApp(android.cdp,androidUrl);pcSnapshot=await localSnapshot(pc.cdp);androidSnapshot=await localSnapshot(android.cdp);await signIn(pcEndpoint,pc.cdp);priorDrive=await capturePriorDrive(pc.cdp);assert.equal(priorDrive,true,'A prior completed Drive snapshot is required so this test can restore it without leaving a synthetic pointer');
 attachmentId=await createSeed(pc.cdp);const firstBackupId=await backup(pc.cdp);assert.match(firstBackupId,/^s5_[a-f0-9]{40}$/);await signIn(androidEndpoint,android.cdp);await restoreRemote(android.cdp);const androidImported=await android.cdp.evaluate(`(async()=>{const note=state.notes.find(item=>item.title===${JSON.stringify(marker)}),attachment=note?.attachmentIds?.[0]?await getAttachmentRecord(note.attachmentIds[0]):null;return {count:state.notes.filter(item=>item.title===${JSON.stringify(marker)}).length,tags:note?.tags||[],name:attachment?.meta?.name,bytes:attachment?.blob?.size||0,hashMatch:Boolean(attachment&&attachment.meta.sha256===(await sha256Blob(attachment.blob)))};})()`);assert.deepEqual(androidImported.tags,['실제교차기기검사']);assert.equal(androidImported.count,1);assert.equal(androidImported.name,'noteplusp-cross-device.pdf');assert.ok(androidImported.bytes>0);assert.equal(androidImported.hashMatch,true);
 await android.cdp.evaluate(`(async()=>{const note=state.notes.find(item=>item.title===${JSON.stringify(marker)});if(!note)throw new Error('imported marker missing');note.title=${JSON.stringify(marker+'-ANDROID')};note.body+=' Android 수정';note.updated=Date.now();await persist();render();return true;})()`);const secondBackupId=await backup(android.cdp);assert.notEqual(secondBackupId,firstBackupId);await restoreRemote(pc.cdp);const pcReturned=await pc.cdp.evaluate(`(async()=>{const note=state.notes.find(item=>item.title===${JSON.stringify(marker+'-ANDROID')}),attachment=note?.attachmentIds?.[0]?await getAttachmentRecord(note.attachmentIds[0]):null;return {count:state.notes.filter(item=>item.title===${JSON.stringify(marker+'-ANDROID')}).length,body:note?.body||'',bytes:attachment?.blob?.size||0,hashMatch:Boolean(attachment&&attachment.meta.sha256===(await sha256Blob(attachment.blob)))};})()`);assert.equal(pcReturned.count,1);assert.match(pcReturned.body,/Android 수정/);assert.ok(pcReturned.bytes>0);assert.equal(pcReturned.hashMatch,true);
 await pc.cdp.evaluate('(async()=>{await noteplusCloud.uploadSnapshot(window.__crossDevicePriorDrive);window.__crossDevicePriorDrive=null;return true;})()');priorRestored=true;await restoreLocal(pc.cdp,pcSnapshot,attachmentId);pcRestored=true;await restoreLocal(android.cdp,androidSnapshot,attachmentId);androidRestored=true;const result={candidate:'v22',cardId:'S1-004',method:'real-account-device',scope:'PC to Android to PC through Google Drive appDataFolder; identifiers omitted',checkedAt:new Date().toISOString(),result:'PASS',sourceHead,checks:['PC synthetic note and PDF backed up','Android restored and verified title/tags/attachment bytes/SHA-256','Android edit backed up','PC restored Android edit and attachment SHA-256','prior Drive pointer restored','both local original signatures restored'],backupIds:[firstBackupId.slice(0,7),secondBackupId.slice(0,7)],cleanup:{priorDrivePointerRestored:priorRestored,pcOriginalRestored:pcRestored,androidOriginalRestored:androidRestored}};fs.writeFileSync(artifact,JSON.stringify(result,null,2));console.log(JSON.stringify({ok:true,cleanup:result.cleanup},null,2));
}finally{
 if(priorDrive&&!priorRestored)await pc.cdp.evaluate('(async()=>{if(window.__crossDevicePriorDrive)await noteplusCloud.uploadSnapshot(window.__crossDevicePriorDrive);})()').catch(()=>{});
 if(pcSnapshot&&!pcRestored)await restoreLocal(pc.cdp,pcSnapshot,attachmentId).catch(()=>{});if(androidSnapshot&&!androidRestored)await restoreLocal(android.cdp,androidSnapshot,attachmentId).catch(()=>{});
 await pc.cdp.evaluate('noteplusCloud?.signOut?.()').catch(()=>{});await android.cdp.evaluate('noteplusCloud?.signOut?.()').catch(()=>{});if(pc.originalUrl&&pc.originalUrl!==pcUrl)await pc.cdp.send('Page.navigate',{url:pc.originalUrl}).catch(()=>{});if(android.originalUrl&&android.originalUrl!==androidUrl)await android.cdp.send('Page.navigate',{url:android.originalUrl}).catch(()=>{});pc.cdp.close();android.cdp.close();
}
