import assert from 'node:assert/strict';
import {harness,ready} from './v22_test_harness.mjs';

const h=await harness();
try{
 const context=await h.browser.newContext(),page=await context.newPage();await ready(page,h.origin+'/노트앱_v22.html');
 const result=await page.evaluate(async()=>{var original=cloneState(state),now=Date.now(),notes=[{id:'search_title',title:'한글 회의',body:'본문',bodyHtml:'본문',notebook:'업무',tags:['중요'],attachmentIds:[],favorite:true,updated:now,created:now},{id:'search_link',title:'연결 노트',body:'프로젝트 지도',bodyHtml:'<a data-note-id="search_title">한글 회의</a>',notebook:'지식',tags:[],attachmentIds:['att_search_pdf'],favorite:false,updated:now-1,created:now-1},{id:'search_special',title:'정규식 [a-z]+ 그대로',body:'<img src=x onerror="searchPwned=1">',bodyHtml:'&lt;img src=x onerror=&quot;searchPwned=1&quot;&gt;',notebook:'개인',tags:['기호'],attachmentIds:[],favorite:false,updated:now-2,created:now-2}];state.notes=notes;state.trash=[{id:'search_trash',title:'휴지통 대상',body:'삭제 검색',bodyHtml:'삭제 검색',notebook:'개인',tags:[],attachmentIds:[],updated:now-3,created:now-3}];state.notebooks=['업무','지식','개인'];v22AttachmentNamesByNote.set('search_link',['계획서.pdf']);window.searchPwned=0;
  var cases={title:v22SearchReasons(notes[0],'한글'),tag:v22SearchReasons(notes[0],'tag:중요'),notebook:v22SearchReasons(notes[0],'nb:업무'),favorite:v22SearchReasons(notes[0],'is:favorite'),attachment:v22SearchReasons(notes[1],'계획서.pdf'),link:v22SearchReasons(notes[1],'has:link'),special:v22SearchReasons(notes[2],'[a-z]+'),html:v22SearchReasons(notes[2],'<img'),negated:v22SearchReasons(notes[0],'-없는말')};
  ui.trash=false;ui.query='삭제';var activeCount=visibleNotes().length;ui.trash=true;var trashCount=visibleNotes().length;ui.trash=false;ui.query='<img';renderList();var rendered=document.querySelector('#listScroll .v22-search-reasons')?.textContent||'',marks=document.querySelectorAll('#listScroll mark').length,htmlExecuted=window.searchPwned;
  var bulk=Array.from({length:10000},function(_,i){return {id:'bulk_'+i,title:'노트 '+i,body:i%2?'alpha':'한글 검색',bodyHtml:i%2?'alpha':'한글 검색',notebook:'대형',tags:['t'+i%5],attachmentIds:[],updated:i+1,created:i+1};}),started=performance.now(),matched=bulk.filter(function(note){return v22SearchReasons(note,'한글 tag:t2').matched;}).length,elapsed=performance.now()-started;
  state=original;render();return {cases,activeCount,trashCount,rendered,marks,htmlExecuted,bulk:{matched,elapsed}};});
 assert.equal(result.cases.title.matched,true);assert.ok(result.cases.title.reasons.includes('제목'));assert.ok(result.cases.tag.reasons.includes('태그'));assert.ok(result.cases.notebook.reasons.includes('노트북'));assert.ok(result.cases.favorite.reasons.includes('즐겨찾기'));assert.ok(result.cases.attachment.reasons.includes('첨부 이름'));assert.ok(result.cases.link.reasons.includes('내부 연결'));assert.equal(result.cases.special.matched,true);assert.equal(result.cases.html.matched,true);assert.equal(result.cases.negated.matched,true);assert.equal(result.activeCount,0);assert.equal(result.trashCount,1);assert.match(result.rendered,/일치/);assert.ok(result.marks>=1);assert.equal(result.htmlExecuted,0);assert.equal(result.bulk.matched,1000);assert.ok(result.bulk.elapsed<500);
 const saved=await page.evaluate(async()=>{ui.query='tag:중요 한글';document.getElementById('search').value=ui.query;document.getElementById('v22SavedFilterName').value='중요 회의';document.getElementById('v22SavedFilterSave').click();await new Promise(resolve=>setTimeout(resolve,20));var stored=cloneState(state.preferences.savedSearches);ui.query='';v22RenderSavedFilters();document.querySelector('[data-saved-filter-run="0"]').click();return {stored,rerun:ui.query};});assert.deepEqual(saved.stored,[{name:'중요 회의',query:'tag:중요 한글'}]);assert.equal(saved.rerun,'tag:중요 한글');
 await context.close();console.log(JSON.stringify({ok:true,card:'S2-003',fieldReasons:['title','body','tag','notebook','attachment-name','internal-link'],safeHighlight:true,regexLikeLiteral:true,korean:true,trashSeparated:true,savedFilterRerun:true,tenThousandMs:Math.round(result.bulk.elapsed)},null,2));
}finally{await h.close();}
