import assert from 'node:assert/strict';
import path from 'node:path';
import {harness,ready,root} from './v22_test_harness.mjs';
const h=await harness();
try{
 const a=await h.browser.newContext(),source=await a.newPage();await ready(source,h.origin+'/노트앱_v22.html');await source.waitForFunction(()=>window.noteplusAdvanced?.ready);await source.locator('#v22SkipWelcome').click();
 await source.locator('#enexFile').setInputFiles(path.join(root,'pilot-assets/노트플러스P_파일럿_샘플.enex'));await source.locator('#importPreviewConfirm').click();await source.waitForFunction(async()=>(await v22BuildCertificate()).status==='일치');
 const exported=await source.evaluate(async()=>{const selected=state.notes.find(n=>n.attachmentIds.length),before=stateSignature(state),blob=await noteplusAdvanced.exportSelected([selected.id],before);const prepared=await v22ReadPortable(blob);noteplusAdvanced.openAttachments();return {bytes:Array.from(new Uint8Array(await blob.arrayBuffer())),id:selected.id,notes:prepared.state.notes.length,attachments:prepared.items.length,unchanged:before===stateSignature(state)};});
 assert.equal(exported.notes,1);assert.equal(exported.attachments,1);assert.equal(exported.unchanged,true);await source.waitForFunction(()=>document.getElementById('v22AttachmentHubResult').textContent.includes('검사 완료'));assert.match(await source.locator('#v22AttachmentHub').innerText(),/원본 있음/);
 const b=await h.browser.newContext(),destination=await b.newPage();await ready(destination,h.origin+'/노트앱_v22.html');await destination.locator('#v22SkipWelcome').click();const restored=await destination.evaluate(async bytes=>{const prepared=await v22ReadPortable(new Blob([new Uint8Array(bytes)]));await v22ApplyPortable(prepared,stateSignature(state));const item=await getAttachmentRecord(prepared.items[0].meta.id);return {notes:state.notes.length,size:item.blob.size,hash:await sha256Blob(item.blob),expected:prepared.items[0].meta.sha256};},exported.bytes);assert.equal(restored.notes,1);assert.equal(restored.size,69);assert.equal(restored.hash,restored.expected);await ready(destination,h.origin+'/노트앱_v22.html');assert.equal(await destination.evaluate(()=>state.notes.length),1);
 await source.evaluate(()=>document.querySelectorAll('dialog[open]').forEach(d=>d.close()));
 await source.evaluate(async()=>{await navigator.serviceWorker.ready;});await source.reload({waitUntil:'networkidle'});await source.waitForFunction(()=>navigator.serviceWorker.controller&&window.noteplusAdvanced?.ready);await a.setOffline(true);await source.goto(h.origin+'/help.html');await source.waitForFunction(()=>document.querySelectorAll('#errors article').length===20);assert.equal(await source.locator('#coreJourneys article').count(),6);await a.setOffline(false);
 await a.close();await b.close();console.log(JSON.stringify({ok:true,selectedZipNotes:1,attachmentBytes:69,hashMatched:true,emptyDestinationRestored:true,reload:true,sourcePreserved:true,offlineHelpErrors:20,actualDeviceRoundtrip:false}));
}finally{await h.close();}
