import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import {fileURLToPath} from "node:url";

const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),"..");
const artifact=path.join(root,"artifacts/physical_android_v22_drive_real_v1.json");
const appUrl=(process.env.NOTEPLUS_ANDROID_V22_URL||"http://127.0.0.1:18799/%EB%85%B8%ED%8A%B8%EC%95%B1_v22.html")+`?drive-real=${Date.now()}`;
const cdpHttp=process.env.NOTEPLUS_ANDROID_CDP||"http://127.0.0.1:9222";
const sourceHead=process.env.NOTEPLUS_SOURCE_HEAD||"";
const marker=`REAL-DRIVE-ANDROID-${Date.now()}`;
const delay=ms=>new Promise(resolve=>setTimeout(resolve,ms));
async function poll(check,timeout=60000,interval=300){const end=Date.now()+timeout;let last;while(Date.now()<end){try{last=await check();if(last)return last;}catch(error){last=error;}await delay(interval);}throw last instanceof Error?last:new Error("poll timeout");}

class CdpTarget{
  constructor(url){this.url=url;this.nextId=1;this.pending=new Map();}
  async connect(){this.ws=new WebSocket(this.url);this.ws.onmessage=event=>{const message=JSON.parse(String(event.data)),pending=this.pending.get(message.id);if(!pending)return;this.pending.delete(message.id);message.error?pending.reject(new Error(`${pending.method}: ${message.error.message}`)):pending.resolve(message.result||{});};await new Promise((resolve,reject)=>{this.ws.onopen=resolve;this.ws.onerror=reject;});}
  send(method,params={},timeout=30000){const id=this.nextId++;return new Promise((resolve,reject)=>{const timer=setTimeout(()=>{this.pending.delete(id);reject(new Error(`${method}: response timeout`));},timeout);this.pending.set(id,{method,resolve:value=>{clearTimeout(timer);resolve(value);},reject:error=>{clearTimeout(timer);reject(error);}});this.ws.send(JSON.stringify({id,method,params}));});}
  async evaluate(expression){const response=await this.send("Runtime.evaluate",{expression,awaitPromise:true,returnByValue:true,userGesture:true},120000);if(response.exceptionDetails)throw new Error(response.exceptionDetails.exception?.description||response.exceptionDetails.text||"Runtime evaluation failed");return response.result?.value;}
  close(){try{this.ws?.close();}catch{}}
}
async function targetList(){const response=await fetch(cdpHttp+"/json/list");assert.equal(response.ok,true);return response.json();}
async function connectMain(){const candidates=(await targetList()).filter(t=>t.type==="page"&&/^https?:/i.test(t.url)&&t.webSocketDebuggerUrl).sort((a,b)=>Number(/noteplusp|127\.0\.0\.1:18799/i.test(b.url))-Number(/noteplusp|127\.0\.0\.1:18799/i.test(a.url))).slice(0,16);for(const info of candidates){const cdp=new CdpTarget(info.webSocketDebuggerUrl);try{await cdp.connect();await cdp.send("Page.enable",{},3000);await cdp.send("Runtime.enable",{},3000);await cdp.send("Page.bringToFront",{},3000);return {cdp,info};}catch{cdp.close();}}throw new Error("responsive Android Chrome page unavailable");}
async function advanceGoogle(main){const deadline=Date.now()+120000,seen=new Set();while(Date.now()<deadline){if(await main.evaluate("Boolean(window.noteplusCloud?.status?.().user)").catch(()=>false))return true;for(const info of (await targetList()).filter(t=>t.type==="page"&&/^https:\/\/accounts\.google\.com\//.test(t.url)&&t.webSocketDebuggerUrl)){if(seen.has(info.id)&&Date.now()%3)continue;seen.add(info.id);const popup=new CdpTarget(info.webSocketDebuggerUrl);try{await popup.connect();await popup.send("Runtime.enable",{},3000);await popup.send("Page.bringToFront",{},3000);const action=await popup.evaluate(`(()=>{const visible=e=>e&&e.getClientRects().length;const account=[...document.querySelectorAll('[data-identifier],[data-authuser]')].find(visible);if(account){account.click();return 'account';}const controls=[...document.querySelectorAll('button,[role="button"],a')].filter(visible);const pick=controls.find(e=>/^(계속|Continue|허용|Allow|고급|Advanced)$/i.test((e.textContent||'').trim()))||controls.find(e=>/안전하지 않음|unsafe/i.test(e.textContent||''));if(pick){pick.click();return 'consent';}return 'wait';})()`);if(action!=="wait")await delay(1000);}catch{}finally{popup.close();}}await main.send("Page.bringToFront",{}).catch(()=>{});await delay(500);}return false;}

const {cdp,info}=await connectMain();const originalUrl=info.url;let originalJson="",originalSignature="",testAttachmentId="",priorDriveFound=false,localRestored=false,priorPointerRestored=false,loggedIn=false;
try{
  console.log("STEP target-connected");await cdp.send("Page.navigate",{url:appUrl},90000);await poll(()=>cdp.evaluate("document.readyState==='complete'||document.readyState==='interactive'"),90000);await poll(()=>cdp.evaluate("Boolean(window.state&&window.storageReady&&typeof window.storageReady.then==='function')"),60000);await cdp.evaluate("window.storageReady");console.log("STEP app-ready");
  await cdp.evaluate("document.querySelector('#v22SkipWelcome')?.click();true");({originalJson,originalSignature}=await cdp.evaluate("({originalJson:JSON.stringify(state),originalSignature:stateSignature(state)})"));
  testAttachmentId=await cdp.evaluate(`(async()=>{const now=Date.now(),note={id:uid(),title:${JSON.stringify(marker)},body:'합성 Drive 실제 계정 왕복 검사',bodyHtml:'<p>합성 Drive 실제 계정 왕복 검사</p>',notebook:state.notebooks[0]||'개인',tags:['실제계정검사'],created:now-1000,updated:now,attachmentIds:[],favorite:false,history:[]};const blob=new Blob(['%PDF-1.4\\nNotePlusP synthetic Drive proof\\n%%EOF\\n'],{type:'application/pdf'}),id='att_'+uid(),meta={id,noteId:note.id,name:'noteplusp-drive-synthetic.pdf',mime:'application/pdf',size:blob.size,created:now,sha256:await sha256Blob(blob)};note.attachmentIds=[id];state.notes.push(note);await writeStateAndAttachments([{meta,blob}],[],null);render();return id;})()`);console.log("STEP synthetic-ready");
  await cdp.send("Page.bringToFront",{});await cdp.evaluate("document.querySelector('#googleSignInBtn').click();true");loggedIn=await advanceGoogle(cdp);assert.equal(loggedIn,true,"Google OAuth did not complete on the connected Android account");console.log("STEP oauth-complete");
  priorDriveFound=await cdp.evaluate(`(async()=>{try{const bundle=await noteplusCloud.downloadCurrentSnapshot(),manifest=bundle.manifest,attachments=[];for(const item of manifest.attachments){attachments.push({id:item.id,blob:await noteplusCloud.downloadAttachment(manifest.snapshotId,item,bundle.accountUid),mime:item.mime,sha256:item.sha256});}const text=JSON.stringify(manifest);window.__priorDrivePayload={snapshotId:manifest.snapshotId,manifestText:text,manifestSha256:await sha256Text(text),attachments,counts:manifest.counts};return true;}catch{return false;}})()`);console.log("STEP prior-pointer-preserved",priorDriveFound);
  await cdp.evaluate("document.querySelector('#cloudBackupBtn').click();true");await poll(()=>cdp.evaluate(`!cloudSnapshotInFlight&&Boolean(v22Status.lastBackupId)&&state.notes.some(n=>n.title===${JSON.stringify(marker)})`),180000);const backupId=await cdp.evaluate("v22Status.lastBackupId");assert.match(backupId,/^s5_[a-f0-9]{40}$/);console.log("STEP backup-complete");
  await cdp.evaluate(`(async()=>{const empty=cloneState(state);empty.notes=[];empty.trash=[];empty.lastImportUndo=null;empty.lastImportReport=null;empty.preferences.snapshots=[];empty.preferences.conflictVaultV1=[];state=migrateState(empty);await persist();render();return true;})()`);
  await cdp.evaluate("document.querySelector('#cloudRestoreBtn').click();true");await poll(()=>cdp.evaluate("Boolean(pendingCloudRestore)&&!cloudSnapshotInFlight"),180000);console.log("STEP preview-ready");await cdp.evaluate("document.querySelector('#cloudRestoreBtn').click();true");await poll(()=>cdp.evaluate("Boolean(document.querySelector('[data-v22-restore=\"remote\"]')?.getClientRects().length)"),30000);await cdp.evaluate("document.querySelector('[data-v22-restore=\"remote\"]').click();true");await poll(()=>cdp.evaluate(`!cloudSnapshotInFlight&&state.notes.some(n=>n.title===${JSON.stringify(marker)})`),180000);
  const restored=await cdp.evaluate(`(async()=>{const note=state.notes.find(n=>n.title===${JSON.stringify(marker)}),item=note&&note.attachmentIds[0]?await getAttachmentRecord(note.attachmentIds[0]):null;return {count:state.notes.filter(n=>n.title===${JSON.stringify(marker)}).length,tags:note?.tags||[],attachmentName:item?.meta?.name,attachmentBytes:item?.blob?.size||0,hashMatch:Boolean(item&&item.meta.sha256===(await sha256Blob(item.blob)))};})()`);assert.equal(restored.count,1);assert.deepEqual(restored.tags,["실제계정검사"]);assert.equal(restored.attachmentName,"noteplusp-drive-synthetic.pdf");assert.ok(restored.attachmentBytes>0);assert.equal(restored.hashMatch,true);console.log("STEP restore-verified");
  if(priorDriveFound){await cdp.evaluate("(async()=>{await noteplusCloud.uploadSnapshot(window.__priorDrivePayload);window.__priorDrivePayload=null;return true;})()");priorPointerRestored=true;}
  await cdp.evaluate(`(async()=>{state=migrateState(JSON.parse(${JSON.stringify(originalJson)}));sanitizeAllNoteHtml(state);await writeStateAndAttachments([],${JSON.stringify(testAttachmentId)}?[${JSON.stringify(testAttachmentId)}]:[],null);render();if(stateSignature(state)!==${JSON.stringify(originalSignature)})throw new Error('original signature mismatch');return true;})()`);localRestored=true;await cdp.evaluate("noteplusCloud.signOut()").catch(()=>{});loggedIn=false;console.log("STEP cleanup-verified");
  const result={candidate:"v22",cardId:"S1-004",method:"real-account-device",environment:"Galaxy S21+ Android Chrome and Google Drive appDataFolder; identifiers omitted",checkedAt:new Date().toISOString(),result:"PASS",sourceHead,checks:["real Google OAuth completed","synthetic note and PDF uploaded","completed pointer recorded once","restore preview before mutation","remote snapshot restored","title, tag, attachment name, bytes and SHA-256 matched","local original signature restored",priorDriveFound?"prior Drive pointer restored":"no prior NotePlusP pointer was available"],limitations:["Same physical Android browser performed upload and restore; this is not PC-to-Android evidence","Test snapshot remains in appDataFolder when no prior pointer existed","No screenshots or account identifiers retained"],backupIdPrefix:backupId.slice(0,7),restored:{count:restored.count,attachmentBytes:restored.attachmentBytes,hashMatch:restored.hashMatch},cleanup:{testDataRemoved:localRestored,originalStateRestored:localRestored,priorDrivePointerRestored:priorPointerRestored||!priorDriveFound}};fs.writeFileSync(artifact,JSON.stringify(result,null,2));console.log(JSON.stringify({ok:true,priorDriveFound,priorPointerRestored,localRestored,restored:result.restored},null,2));
}finally{
  if(originalJson&&!localRestored)await cdp.evaluate(`(async()=>{state=migrateState(JSON.parse(${JSON.stringify(originalJson)}));sanitizeAllNoteHtml(state);await writeStateAndAttachments([],${JSON.stringify(testAttachmentId)}?[${JSON.stringify(testAttachmentId)}]:[],null);render();return true;})()`).catch(()=>{});
  if(priorDriveFound&&!priorPointerRestored)await cdp.evaluate("(async()=>{if(window.__priorDrivePayload)await noteplusCloud.uploadSnapshot(window.__priorDrivePayload);})()").catch(()=>{});
  if(loggedIn)await cdp.evaluate("noteplusCloud?.signOut?.()").catch(()=>{});if(originalUrl&&originalUrl!==appUrl)await cdp.send("Page.navigate",{url:originalUrl}).catch(()=>{});cdp.close();console.log("STEP original-tab-restored");
}
