import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const core=fs.readFileSync(path.join(root,'노트앱_core_v22.html'),'utf8');
const help=fs.readFileSync(path.join(root,'help.html'),'utf8');
const worker=fs.readFileSync(path.join(root,'sw-v22.js'),'utf8');
const content=JSON.parse(fs.readFileSync(path.join(root,'content','content-ko-v1.json'),'utf8'));
assert.equal(content.locale,'ko-KR');
assert.equal(content.coreJourneys.length,6);assert.equal(content.terms.length,5);assert.equal(content.emptyStates.length,12);assert.equal(content.successStates.length,10);
assert.ok(core.indexOf('function v22VaultItems')<core.indexOf('var v22Status='),'conflict accessor must be declared in the initial status script before async callbacks');
assert.equal(content.journeys.length,6,'exactly six guided journeys');
assert.equal(content.errors.length,20,'exactly twenty recovery cards');
assert.equal(new Set(content.journeys.map(x=>x.id)).size,6,'journey ids unique');
assert.equal(new Set(content.errors.map(x=>x.id)).size,20,'error ids unique');
for(const item of [...content.journeys,...content.errors]) assert.ok(item.title&&item.id,'content needs id and title');
for(const item of content.errors) assert.ok(item.cause&&item.action,'error needs cause and action');
for(const name of ['빠른 메모','회의록','할 일','학습 노트','여행 계획','주간 회고']) assert.match(core,new RegExp(`name:"${name}"`));
assert.match(core,/검색 결과가 없습니다/);
assert.match(core,/help\.html#recovery/);
assert.match(core,/Google Drive 연결/);
assert.doesNotMatch(core,/Google로 로그인·무료 가입/);
assert.match(help,/id="start"/);assert.match(help,/id="recovery"/);
assert.match(worker,/noteplusp-v22-shell-7/);assert.match(worker,/\.\/help\.html/);assert.match(worker,/\.\/content\/content-ko-v1\.json/);assert.match(worker,/\.\/noteplus-stage3-v22\.js/);
console.log('PASS v22 content stage 1 has 6 journeys, 20 recovery cards, 6 templates, contextual empty states, accurate Drive wording and offline help');
