import assert from 'node:assert/strict';
import path from 'node:path';
import {harness,ready,root} from './v22_test_harness.mjs';
const h=await harness();
try{const a=await h.browser.newContext(),page=await a.newPage();await ready(page,h.origin+'/노트앱_v22.html');await page.locator('#v22SkipWelcome').click();
 await page.locator('#enexFile').setInputFiles(path.join(root,'pilot-assets/노트플러스P_파일럿_샘플.enex'));await page.locator('#importPreviewConfirm').click();await page.waitForFunction(async()=>(await v22BuildCertificate()).status==='일치');
 const exported=await page.evaluate(async()=>{
  const attachmentNote=state.notes.find(n=>n.attachmentIds.length),active=state.notes.find(n=>n.id!==attachmentNote.id),marker='PORTABLE-COMPLEX-NOTE';
  active.title=marker;active.tags=['한글 태그','portable'];active.created=946684800000;active.updated=946684860000;active.body='연결 대상 #note:'+attachmentNote.id;active.bodyHtml='<p>연결 대상 <a href="#note:'+attachmentNote.id+'" data-note-id="'+attachmentNote.id+'">열기</a></p>';active.history=[{at:946684830000,title:'이전 제목',body:'이전 본문',bodyHtml:'<p>이전 본문</p>',tags:['이력'],notebook:active.notebook||'',favorite:false}];
  state.preferences.snapshots=[{at:946684850000,reason:'전체 왕복 검사',data:cloneSnapshotData()}];state.preferences.conflictVaultV1=[{conflictId:'portable_conflict_1',noteId:active.id,localUpdatedAt:active.updated,remoteUpdatedAt:active.updated+1,localCopy:cloneState(active),remoteCopy:Object.assign(cloneState(active),{body:'원격 보존 본문',bodyHtml:'<p>원격 보존 본문</p>',updated:active.updated+1}),localTrash:false,remoteTrash:false,resolution:'both',resolvedAt:null}];
  state.notes=state.notes.filter(n=>n.id!==attachmentNote.id);attachmentNote.deletedAt=Date.now();state.trash.push(attachmentNote);state.preferences.futureSetting={retained:true};await persist();
  const original=stateSignature(state),expected=migrateState(cloneState(state));sanitizeAllNoteHtml(expected);const jsonAttachments=await collectExportAttachments();const zip=await v22ExportPortable();window.exportedZip=zip;return {bytes:Array.from(new Uint8Array(await zip.arrayBuffer())),signature:stateSignature(expected),sourceUnchanged:original===stateSignature(state),jsonAttachmentCount:jsonAttachments.length,attachmentIds:attachmentNote.attachmentIds,marker,targetId:attachmentNote.id};
 });assert.equal(exported.jsonAttachmentCount,1);assert.equal(exported.sourceUnchanged,true);
 const b=await h.browser.newContext(),destination=await b.newPage();await ready(destination,h.origin+'/노트앱_v22.html');await destination.locator('#v22SkipWelcome').click();
 const restored=await destination.evaluate(async({bytes,marker,targetId})=>{const prepared=await v22ReadPortable(new Blob([new Uint8Array(bytes)]));await v22ApplyPortable(prepared,stateSignature(state));const id=prepared.items[0].meta.id,item=await getAttachmentRecord(id),note=state.notes.find(n=>n.title===marker);return {signature:stateSignature(state),blobSize:item.blob.size,dates:note.created===946684800000&&note.updated===946684860000,tags:note.tags.join('|'),history:note.history.length===1&&note.history[0].title==='이전 제목',link:note.body.includes(targetId)&&note.bodyHtml.includes(targetId),snapshot:state.preferences.snapshots.length===1&&state.preferences.snapshots[0].reason==='전체 왕복 검사',vault:state.preferences.conflictVaultV1.length===1&&state.preferences.conflictVaultV1[0].remoteCopy.body==='원격 보존 본문',future:state.preferences.futureSetting?.retained===true,trash:state.trash.some(n=>n.id===targetId)};},{bytes:exported.bytes,marker:exported.marker,targetId:exported.targetId});assert.equal(restored.signature,exported.signature);assert.equal(restored.blobSize,69);assert.deepEqual({...restored,signature:undefined,blobSize:undefined},{signature:undefined,blobSize:undefined,dates:true,tags:'한글 태그|portable',history:true,link:true,snapshot:true,vault:true,future:true,trash:true});
 await ready(destination,h.origin+'/노트앱_v22.html');assert.equal(await destination.evaluate(()=>stateSignature(state)),exported.signature);
 assert.equal(await destination.evaluate(async bytes=>{const before=stateSignature(state);try{await v22ApplyPortable(await v22ReadPortable(new Blob([new Uint8Array(bytes)])),before);return false;}catch{ return before===stateSignature(state);}},exported.bytes),true);
 const negatives=await page.evaluate(async()=>{let blocked=0;for(const paths of [['../evil'],['x','x'],['/absolute'],['C:/escape']]){try{await noteplusPortable.encode(paths.map(path=>({path,blob:new Blob(['a'])})));}catch{blocked++;}}const data=new Uint8Array(await exportedZip.arrayBuffer());data[100]^=1;try{await v22ReadPortable(new Blob([data]));}catch{blocked++;}return blocked;});assert.equal(negatives,5);
 // Cancelling permanent deletion must preserve both note state and its PDF.
 await destination.evaluate(()=>{ui.trash=true;ui.selectedId=state.trash[0].id;render();});destination.on('dialog',dialog=>dialog.dismiss());
 await destination.locator('#delBtn').click();await destination.locator('#delBtn').click();assert.equal(await destination.evaluate(()=>stateSignature(state)),exported.signature);
 await a.close();await b.close();console.log('PASS v22 ZIP complex notes+links+history+snapshots+conflicts+trash PDF roundtrip, settings, reload, guard and corruption rejection');
}finally{await h.close();}
