import assert from 'node:assert/strict';
import {harness,ready} from './v22_test_harness.mjs';

const h=await harness();
try{
 const context=await h.browser.newContext(),page=await context.newPage();await ready(page,h.origin+'/노트앱_v22.html');
 const result=await page.evaluate(()=>{var original=cloneState(state),now=Date.now(),make=(id,title,html='')=>({id,title,body:title,bodyHtml:html,notebook:'지식',tags:[],attachmentIds:[],favorite:false,updated:now,created:now});state.notes=[make('a','A','<a data-note-id="b">B</a><a data-note-id="missing">없음</a>'),make('b','B','<a data-note-id="c">C</a>'),make('c','C'),make('orphan','고립')];state.trash=[];ui.selectedId='b';var first=v22BuildLinkIndex(state);state.notes.find(n=>n.id==='a').title='A 이름 변경';var renamed=v22BuildLinkIndex(state);var removed=state.notes.splice(state.notes.findIndex(n=>n.id==='c'),1)[0];state.trash.push(removed);var deleted=v22BuildLinkIndex(state);state.trash.pop();state.notes.push(removed);var restored=v22BuildLinkIndex(state),before=stateSignature(state);v22RenderLinkDiscovery();var summary=document.getElementById('v22LinkDiscoverySummary').textContent,displayedIncoming=Array.from(document.querySelectorAll('#v22IncomingLinks button')).map(x=>x.textContent),after=stateSignature(state);state=original;render();return {first:{nodes:first.nodeCount,edges:first.edgeCount,incomingB:first.incoming.get('b'),outgoingB:first.outgoing.get('b'),broken:first.broken,orphans:first.orphans},renamedTitle:renamed.byId.get('a').title,deleted:{edges:deleted.edgeCount,broken:deleted.broken},restored:{edges:restored.edgeCount,broken:restored.broken},summary,displayedIncoming,before,after};});
 assert.equal(result.first.nodes,4);assert.equal(result.first.edges,2);assert.deepEqual(result.first.incomingB,['a']);assert.deepEqual(result.first.outgoingB,['c']);assert.deepEqual(result.first.orphans,['orphan']);assert.equal(result.first.broken.length,1);assert.equal(result.renamedTitle,'A 이름 변경');assert.equal(result.deleted.edges,1);assert.equal(result.deleted.broken.length,2);assert.equal(result.restored.edges,2);assert.equal(result.restored.broken.length,1);assert.match(result.summary,/깨진 연결 1개/);assert.deepEqual(result.displayedIncoming,['A 이름 변경']);assert.equal(result.before,result.after);
 const bulk=await page.evaluate(()=>{var notes=Array.from({length:10000},(_,i)=>({id:'n'+i,title:'N'+i,body:'',bodyHtml:i<9999?'<a data-note-id="n'+(i+1)+'">다음</a>':'',notebook:'대형',tags:[],attachmentIds:[],updated:i+1,created:i+1})),started=performance.now(),index=v22BuildLinkIndex({notes});return {nodes:index.nodeCount,edges:index.edgeCount,broken:index.broken.length,orphans:index.orphans.length,elapsed:performance.now()-started};});assert.deepEqual({nodes:bulk.nodes,edges:bulk.edges,broken:bulk.broken,orphans:bulk.orphans},{nodes:10000,edges:9999,broken:0,orphans:0});assert.ok(bulk.elapsed<1000);
 await context.close();console.log(JSON.stringify({ok:true,card:'S2-004',incomingOutgoing:true,brokenLinks:true,orphans:true,titleRenameRecalculated:true,deleteRestoreRecalculated:true,sourceUnchanged:true,tenThousandMs:Math.round(bulk.elapsed)},null,2));
}finally{await h.close();}
