import assert from 'node:assert/strict';
import {harness,ready} from './v22_test_harness.mjs';
const h=await harness();
async function seed(page,corrupt=false){return page.evaluate(async corrupt=>{const note=state.notes[0],id='att_legacy_original',blob=new Blob(['OLD']);note.attachmentIds=[id];note.body=note.bodyHtml='original';await writeAttachmentBatch([{meta:{id,noteId:note.id,name:'synthetic.bin',mime:'application/octet-stream',size:3,sha256:corrupt?'A'.repeat(64):await sha256Blob(blob)},blob}]);await persist();return JSON.stringify(state);},corrupt);}
try {
 const context=await h.browser.newContext(),page=await context.newPage();await ready(page,h.origin+'/노트앱_v21.html');const before=await seed(page);
 await ready(page,h.origin+'/노트앱_v22.html');assert.equal(await page.evaluate(()=>JSON.stringify(state)),before);assert.equal(await page.evaluate(()=>DB_NAME),'noteplusp_v22_schema5');assert.equal(await page.evaluate(()=>v22StorageMigration.attachmentCount),1);
 await page.evaluate(async()=>{const local=cloneState(state.notes[0]),remote=cloneState(local),id='att_legacy_vault_only';remote.attachmentIds=[id];state.notes[0].body=state.notes[0].bodyHtml='v22-only';state.preferences.conflictVaultV1=[{conflictId:'legacy-boundary',noteId:local.id,localCopy:local,remoteCopy:remote,resolvedAt:null}];const blob=new Blob(['NEW']);await writeAttachmentBatch([{meta:{id,noteId:local.id,name:'synthetic.bin',mime:'application/octet-stream',size:3,sha256:await sha256Blob(blob)},blob}]);await persist();});
 await ready(page,h.origin+'/노트앱_v21.html');assert.equal(await page.evaluate(()=>JSON.stringify(state)),before);
 const legacy=await page.evaluate(async()=>{const removed=await cleanupOrphanAttachments();state.notes[0].body=state.notes[0].bodyHtml='legacy-later';await persist();return {removed,vaultBlob:!!(await getAttachmentRecord('att_legacy_vault_only')),original:(await getAttachmentRecord('att_legacy_original')).blob.size};});assert.deepEqual(legacy,{removed:0,vaultBlob:false,original:3});
 await ready(page,h.origin+'/노트앱_v22.html');assert.equal(await page.evaluate(()=>state.notes[0].body),'v22-only');assert.equal(await page.evaluate(async()=>await (await getAttachmentRecord('att_legacy_vault_only')).blob.text()),'NEW');assert.equal(await page.evaluate(()=>v22StorageMigration),null);await context.close();
 for(const failure of ['corrupt','quota']){const c=await h.browser.newContext(),p=await c.newPage();await ready(p,h.origin+'/노트앱_v21.html');const original=await seed(p,failure==='corrupt');if(failure==='quota')await p.addInitScript(()=>{navigator.storage.estimate=async()=>({usage:100,quota:101});});await ready(p,h.origin+'/노트앱_v22.html');assert.equal(await p.locator('#v22StorageBlocked').evaluate(d=>d.open),true);assert.equal(await p.evaluate(()=>v22StorageIsolationBlocked),true);assert.equal(await p.evaluate(()=>localStorage.getItem('notes_app_v22_schema5_fallback')),null);assert.equal(await p.evaluate(async()=>{const db=await openNoteDatabase();const root=await new Promise((resolve,reject)=>{const req=db.transaction('app_state').objectStore('app_state').get('root');req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error);});db.close();return root===undefined;}),true);await ready(p,h.origin+'/노트앱_v21.html');assert.equal(await p.evaluate(()=>JSON.stringify(state)),original);assert.equal(await p.evaluate(async()=>await (await getAttachmentRecord('att_legacy_original')).blob.text()),'OLD');await c.close();}
 console.log(JSON.stringify({ok:true,legacyReadonlyCopy:true,independentEdits:true,legacyCleanupCannotReachV22Vault:true,reload:true,corruptAndQuotaBlocked:true,sourceUnchanged:true,scope:'isolated synthetic profiles; small attachments; not large-library migration or real Android'},null,2));
} finally {await h.close();}
