import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),"..");
const html=fs.readFileSync(path.join(root,"index.html"),"utf8");
const css=fs.readFileSync(path.join(root,"site-home.css"),"utf8");
const plan=fs.readFileSync(path.join(root,"SITE_CONTENT_UX_PLAN_v1.md"),"utf8");
for(const required of ["노트플러스P — 기록을 안전하게 옮기고 오래 쓰는 노트","지금 노트 시작하기","Evernote 전체 이전 가이드","안전과 신뢰","정식 공개판과 개발판을 구분합니다","현재 공개","1단계","2단계","3단계"])assert.ok(html.includes(required),`missing home content: ${required}`);
for(const href of ["노트앱_v21.html","guides.html","guide-evernote-migration.html","guide-data-safety.html","privacy.html","support.html","artifacts/noteplusp_v21_qr.png"])assert.ok(html.includes(`href=\"${href}\"`)||html.includes(`src=\"${href}\"`),`missing public route: ${href}`);
for(const semantic of ["<header","<nav","<main","<section","<footer","<h1","<h2"])assert.ok(html.includes(semantic),`missing semantic element: ${semantic}`);
const ids=[...html.matchAll(/\sid="([^"]+)"/g)].map(match=>match[1]);
assert.equal(new Set(ids).size,ids.length,"duplicate ids are not allowed");
assert.ok(html.includes('class="skip-link" href="#main"'),"skip link must target main");
assert.ok(!/<script\b/i.test(html),"public home must not add scripts or tracking");
assert.ok(!/adsbygoogle|doubleclick|googlesyndication/i.test(html),"product home stays ad-free");
assert.ok(!/노트앱_v22\.html/.test(html),"unreleased candidate must not be linked");
for(const rule of ["@media (max-width:1100px)","@media (max-width:760px)","@media (max-width:420px)","prefers-reduced-motion",":focus-visible"])assert.ok(css.includes(rule),`missing responsive/accessibility rule: ${rule}`);
for(const heading of ["콘텐츠 지도","핵심 사용자 흐름","시각 체계","반응형·접근성","콘텐츠 진실성 규칙","완료 조건"])assert.ok(plan.includes(heading),`missing plan section: ${heading}`);
console.log(JSON.stringify({ok:true,contract:"site-home-redesign-v1",ids:ids.length,htmlBytes:Buffer.byteLength(html),cssBytes:Buffer.byteLength(css)},null,2));
