// Opt-in release evidence: 10,000 synthetic Korean notes and 1GiB across mixed attachment families.
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import {harness,ready,root} from './v22_test_harness.mjs';
if(process.env.NOTEPLUS_LARGE_E2E!=='1')throw new Error('Set NOTEPLUS_LARGE_E2E=1 after checking at least 3GiB free RAM and 5GiB free disk.');
const proofRoot=path.resolve(root,'../.project-continuity/local/v22-20260826');fs.mkdirSync(proofRoot,{recursive:true});const persistentPath=fs.mkdtempSync(path.join(proofRoot,'mixed-large-profile-'));
const h=await harness({persistentPath});
try{const context=await h.browser.newContext(),page=await context.newPage();await ready(page,h.origin+'/노트앱_v22.html');await page.locator('#v22SkipWelcome').click();await page.waitForFunction(()=>!v22WelcomeBusy&&!v22Welcome.open);
 const fixture=await page.evaluate(async()=>{
  window.mixedOriginal=cloneState(state);window.mixedStarted=performance.now();window.mixedGap=0;window.mixedBeat=performance.now();window.mixedTimer=setInterval(()=>{const t=performance.now();mixedGap=Math.max(mixedGap,t-mixedBeat);mixedBeat=t;},20);
  const variants=[
   {key:'pdf',mime:'application/pdf',name:'중복 이름.pdf',lead:'%PDF-1.7\n'},
   {key:'jpeg-exif-orientation',mime:'image/jpeg',name:'회전 사진.jpg',lead:'\u00ff\u00d8\u00ff\u00e1Exif\u0000\u0000Orientation=6\n'},
   {key:'png',mime:'image/png',name:'중복 이름.png',lead:'\u0089PNG\r\n\u001a\n'},
   {key:'audio',mime:'audio/mpeg',name:'음성 메모.mp3',lead:'ID3\u0004\u0000\u0000'},
   {key:'office-shape',mime:'application/vnd.openxmlformats-officedocument.wordprocessingml.document',name:'문서 모양.docx',lead:'PK\u0003\u0004[Content_Types].xml'},
   {key:'generic',mime:'application/octet-stream',name:'중복 이름.bin',lead:'NOTEPLUS-MIXED-BINARY\n'}
  ];
  window.mixedVariants=[];
  for(let i=0;i<variants.length;i++){const v=variants[i],fill=String.fromCharCode(65+i),raw=(v.lead+fill.repeat(1024*1024)).slice(0,1024*1024),bytes=Uint8Array.from(raw,c=>c.charCodeAt(0)),blob=new Blob([bytes],{type:v.mime});mixedVariants.push({...v,base64:btoa(raw),hash:await sha256Blob(blob),size:blob.size});}
  return {files:16,notes:10000,attachments:1024,decodedBytes:1024**3,variantCounts:Object.fromEntries(variants.map((v,i)=>[v.key,Math.floor(1024/variants.length)+(i<1024%variants.length?1:0)])),formats:variants.map(v=>v.key),privacy:'deterministic synthetic only',inputMode:'16 files selected and processed sequentially to bound memory',storage:await navigator.storage.estimate()};
 });console.log(JSON.stringify({step:'fixture',...fixture}));
 for(let b=0;b<16;b++){
  await page.evaluate(b=>{const parts=['<en-export>'];for(let j=0;j<625;j++){const i=b*625+j;parts.push(`<note><title>혼합 자료 ${i}</title><content><![CDATA[<en-note><div>한글 본문 ${i} · 내부 연결 #note:synthetic-${Math.max(0,i-1)}</div></en-note>]]></content><created>${2000+i%25}0101T000000Z</created><updated>${2000+i%25}0101T010000Z</updated><tag>혼합-${i%9}</tag><tag>synthetic-only</tag>`);if(j<64){const v=mixedVariants[(b*64+j)%mixedVariants.length];parts.push(`<resource><data encoding="base64">${v.base64}</data><mime>${v.mime}</mime><resource-attributes><file-name>${v.name}</file-name></resource-attributes></resource>`);}parts.push('</note>');}parts.push('</en-export>');const file=new File(parts,`mixed-${String(b).padStart(2,'0')}.enex`);document.getElementById('enexFile').onchange({target:{files:[file],value:''}});return true;},b);
  await page.waitForFunction(()=>Boolean(window.pendingEnexImport),null,{timeout:120000});await page.locator('#importPreviewSelectAll').click();await page.locator('#importPreviewConfirm').click();await page.waitForFunction(count=>state.notes.length===count&&state.lastImportReport?.importedNoteCount===625&&!v22ImportCommitPending,1+(b+1)*625,{timeout:180000});console.log(JSON.stringify({step:'batch-stored',batch:b+1,notes:(b+1)*625}));
 }
 const imported=await page.evaluate(async()=>{await persist();clearInterval(mixedTimer);return {notes:state.notes.length,unchangedOriginal:JSON.stringify(state.notes.find(n=>n.id===mixedOriginal.notes[0].id))===JSON.stringify(mixedOriginal.notes[0]),maxGap:Math.round(mixedGap),durationMs:Math.round(performance.now()-mixedStarted),report:state.lastImportReport.outcome,persistenceLimited:state.lastImportReport.persistenceLimited,attachmentErrors:state.lastImportReport.attachmentErrorCount,storage:await navigator.storage.estimate(),expected:mixedVariants.map(v=>({key:v.key,mime:v.mime,size:v.size,hash:v.hash}))};});
 await ready(page,h.origin+'/노트앱_v22.html');const stored=await page.evaluate(async expected=>{const byMime={},names={},seen=new Set();let count=0,bytes=0,mismatches=0,duplicates=0;for(const n of state.notes){if(seen.has(n.id))duplicates++;seen.add(n.id);for(const id of n.attachmentIds||[]){const item=await getAttachmentRecord(id);if(!item){mismatches++;continue;}count++;bytes+=item.blob.size;byMime[item.meta.mime]=(byMime[item.meta.mime]||0)+1;names[item.meta.name]=(names[item.meta.name]||0)+1;const match=expected.find(x=>x.mime===item.meta.mime);if(!match||item.blob.size!==match.size||await sha256Blob(item.blob)!==match.hash)mismatches++;}}return {notes:state.notes.length,attachments:count,bytes,mismatches,duplicates,mimes:Object.keys(byMime).sort(),duplicateNames:Object.values(names).some(v=>v>1),mode:persistenceMode,readers:activeEnexJob?.readers.length||0};},imported.expected);
 assert.equal(imported.notes,10001);assert.equal(imported.unchangedOriginal,true);assert.equal(imported.report,'completed');assert.equal(imported.persistenceLimited,false);assert.equal(imported.attachmentErrors,0);assert.equal(stored.notes,10001);assert.equal(stored.attachments,1024);assert.equal(stored.bytes,1024**3);assert.equal(stored.mismatches,0);assert.equal(stored.duplicates,0);assert.equal(stored.mimes.length,6);assert.equal(stored.duplicateNames,true);assert.equal(stored.mode,'idb');assert.equal(stored.readers,0);assert.ok(imported.maxGap<2000);
 const result={candidate:'v22',cardId:'S1-007',method:'attachment-rich-dataset',environment:'Disposable desktop Edge profile; deterministic synthetic data only',checkedAt:new Date().toISOString(),result:'PASS',sourceHead:process.env.NOTEPLUS_SOURCE_HEAD||'',checks:['10,000 imported notes plus one preserved existing note','1,024 attachments totaling exactly 1GiB','PDF, JPEG with orientation marker, PNG, audio, Office-shaped and generic binary families','Korean titles, bodies, tags, varied dates, internal-link text and duplicate filenames','IndexedDB reload','all attachment size and SHA-256 values matched','missing attachments 0','duplicate note IDs 0','reader leaks 0','existing state unchanged'],limitations:['Synthetic deterministic corpus, not personal production data','Desktop Edge only, not Android','Files are format-shaped safety fixtures, not full Office/media decoder conformance','16 ENEX files processed sequentially to bound memory'],fixture,imported:{notes:imported.notes,maxGap:imported.maxGap,durationMs:imported.durationMs,attachmentErrors:imported.attachmentErrors},stored,cleanup:{testDataRemoved:false,originalStateRestored:false,reason:'Disposable profile retained under continuity local evidence; no personal data'}};
 fs.writeFileSync(path.join(root,'artifacts/v22_mixed_large_library_v1.json'),JSON.stringify(result,null,2));await context.close();console.log(JSON.stringify({ok:true,notes:stored.notes,attachments:stored.attachments,bytes:stored.bytes,mimes:stored.mimes.length,mismatches:stored.mismatches,duplicates:stored.duplicates,maxGap:imported.maxGap,durationMs:imported.durationMs},null,2));
}finally{await h.close();}
