// Opt-in: synthetic 1GiB source plus independent v22 copy, never a personal profile.
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import {harness,ready,root} from './v22_test_harness.mjs';
if(process.env.NOTEPLUS_LARGE_E2E!=='1')throw new Error('Requires NOTEPLUS_LARGE_E2E=1, 3GiB free RAM and 5GiB free disk.');
const base=path.resolve(root,'../.project-continuity/local/v22-20260826');fs.mkdirSync(base,{recursive:true});const persistentPath=fs.mkdtempSync(path.join(base,'legacy-copy-profile-')),h=await harness({persistentPath});
try{const page=await h.browser.newPage();await ready(page,h.origin+'/노트앱_v21.html');
 const source=await page.evaluate(async()=>{const blob=new Blob(['L'.repeat(1024*1024)]),hash=await sha256Blob(blob),notes=[],items=[];for(let i=0;i<10000;i++){const id='legacy-note-'+i,aid='att_legacy_large_'+i;notes.push({id,title:'Synthetic '+i,body:'source '+i,bodyHtml:'source '+i,tags:['synthetic'],notebook:'legacy',created:1,updated:2,attachmentIds:i<1024?[aid]:[],favorite:false,history:[]});if(i<1024)items.push({meta:{id:aid,noteId:id,name:'synthetic.bin',mime:'application/octet-stream',size:blob.size,sha256:hash},blob});}for(let i=0;i<items.length;i+=64)await writeAttachmentBatch(items.slice(i,i+64));state.notes=notes;state.trash=[];state.notebooks=['legacy'];state.preferences.snapshots=[];await persist();return {notes:notes.length,attachments:items.length,bytes:items.length*blob.size,hash,signature:await sha256Text(JSON.stringify(state))};});console.log(JSON.stringify({step:'source-stored',...source}));
 const started=Date.now();await ready(page,h.origin+'/노트앱_v22.html');const copied=await page.evaluate(async hash=>{let count=0,bytes=0,mismatches=0;for(const note of state.notes)for(const id of note.attachmentIds){const item=await getAttachmentRecord(id);if(!item){mismatches++;continue;}count++;bytes+=item.blob.size;if(await sha256Blob(item.blob)!==hash)mismatches++;}return {notes:state.notes.length,attachments:count,bytes,mismatches,signature:await sha256Text(JSON.stringify(state)),database:DB_NAME,migration:v22StorageMigration};},source.hash);assert.equal(copied.signature,source.signature);assert.equal(copied.attachments,1024);assert.equal(copied.bytes,1024**3);assert.equal(copied.mismatches,0);assert.equal(copied.database,'noteplusp_v22_schema5');
 await page.evaluate(async()=>{state.notes[0].body=state.notes[0].bodyHtml='v22 independent';await persist();});await ready(page,h.origin+'/노트앱_v21.html');assert.equal(await page.evaluate(()=>sha256Text(JSON.stringify(state))),source.signature);await ready(page,h.origin+'/노트앱_v22.html');assert.equal(await page.evaluate(()=>state.notes[0].body),'v22 independent');
 console.log(JSON.stringify({ok:true,source,copied,elapsedMs:Date.now()-started,sourceUnchanged:true,reloadIndependent:true,profileDirectory:path.basename(persistentPath),scope:'10,000 synthetic notes and repeated 1GiB binary source copied to independent v22 IndexedDB; desktop Edge only'},null,2));
}finally{await h.close();}
